name: build_wasm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Compile code with wasm-pack
      run: wasm-pack build --target web
    - name: Copy files & Delete .gitignore
      run: mkdir build && cp -r pkg index.html build && rm build/pkg/.gitignore
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build
